<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TcaTrolley" Id="{f529d72a-4dd4-4b6b-8f26-524d47f7e88a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcaTrolley EXTENDS TcoCore.TcoComponent

VAR CONSTANT
	MAX_CARRIERPLACES : INT := 63;
END_VAR


VAR PERSISTENT
	_data : TcaTrolleyData;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Data" Id="{83c5109e-419f-447d-8e5c-89b732984431}">
      <Declaration><![CDATA[PROPERTY Data : REFERENCE TO TcaTrolleyData]]></Declaration>
      <Get Name="Get" Id="{ea7d11fb-c7ac-48f9-a6e1-fbf3a4992164}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Data REF= _data;
]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{813e5464-04f3-4883-8a7d-df90c0cd049a}">
        <Declaration><![CDATA[
VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[_data := Data;
]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="Restore" Id="{d48b6476-49af-43a2-8ee6-0d18ee96d012}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD Restore : TcoCore.ITcoRestorable
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ServiceMode" Id="{0366d0b8-be6d-4911-9590-379d02ca1371}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
(*~
	<docu>
		<summary>
		    Custom service (manual, maintenance) logic.
			This method must be implemented in derived class.
		</summary>			
	</docu>	
~*)
METHOD PROTECTED ServiceMode
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>