<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TcoSegmentDoor_Close" Id="{4f1e7c88-97a5-4883-b1d3-e7f7f73a8c0b}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcoSegmentDoor_Close EXTENDS TcoCore.TcoSequencer
VAR
	_o : TcoCore.TcoSequencerObserver(THIS^);	
	_dialog : TcoCore.TcoDialog(THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="Context" Id="{036130e7-03f6-4401-b264-b8f4f275ce33}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Context : TcoCore.ITcoContext
]]></Declaration>
      <Get Name="Get" Id="{ca87d0d3-e205-4e93-b725-844dac76e36a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="CurrentStep" Id="{3c1762ca-4f0d-4b77-b81f-d95962b69969}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
(*~
	<docu>
		<summary>
			Gets the information about the current step.						
		</summary>				
	</docu>	
~*)
PROPERTY CurrentStep : REFERENCE TO TcoCore.StepDetails
]]></Declaration>
      <Get Name="Get" Id="{06e767db-d1be-4894-8a3e-34d6a4e30c17}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Identity" Id="{6c688134-13b1-4f94-b023-7153aaf3ad67}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Identity : ULINT
]]></Declaration>
      <Get Name="Get" Id="{d76293e8-3be7-4128-992f-9a6f5771ca8b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsAutoRestoreEnabled" Id="{4179be0b-8f38-4e5d-bdd0-c9cd9111d948}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY IsAutoRestoreEnabled : BOOL
]]></Declaration>
      <Get Name="Get" Id="{b1a17375-9ded-43e7-a35c-747bb9e3c6c5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsFreshState" Id="{1a8fc16c-7241-42fd-bd49-1b3ef733029a}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY IsFreshState : BOOL
]]></Declaration>
      <Get Name="Get" Id="{3bb57f92-d416-4ed9-86c6-41148f2d4b53}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="LastStateChangeCycle" Id="{0f2d927a-59ca-46d8-9793-eef8b0211f0e}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY LastStateChangeCycle : ULINT
]]></Declaration>
      <Get Name="Get" Id="{8c37f72a-d4e6-48d1-8ae9-b55fa5cd1cf6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Main" Id="{89467f8d-8a59-4d01-b068-bcd5624f7577}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
(*~
	<docu>
		<summary>
			Main method of the sequener. Custom code needs to be placed here. The sequencer is executed by call of **Instance.Run()** method.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED Main : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="ModeController" Id="{a657e86b-ac68-4b0f-add5-c0373791c437}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY ModeController : TcoCore.ITcoSequencerModeController
]]></Declaration>
      <Get Name="Get" Id="{af1b9034-9afb-43c7-978f-cc59cf099bc3}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="MoveNext" Id="{90c5dbb8-eb0e-40aa-a8d2-f8e505067a60}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD MoveNext : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Restore" Id="{3bc01d8c-9856-46c8-8a37-c9739d852b77}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD Restore : TcoCore.ITcoRestorable
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="RestoreObject" Id="{c68e033a-d176-4d2a-a3f9-486778096ccb}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD RestoreObject : TcoCore.ITcoObjectRestorer
VAR_INPUT
	Obj	: TcoCore.ITcoRestorable;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Retry" Id="{e7b9d5cf-949e-480e-83a3-425f09aa96f6}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD Retry : BOOL
VAR_INPUT
	inFromState	: INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="State" Id="{39d97dc5-ee8b-4204-86f8-6e5423ba3960}">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY State : INT
]]></Declaration>
      <Get Name="Get" Id="{89f7fbcd-9547-4c9d-9deb-64c20e236161}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Terminate" Id="{9c858178-d788-4632-81d6-6074a2018404}">
      <Declaration><![CDATA[{warning 'Methodenimplementierung hinzufügen'}
METHOD Terminate : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>